### PR TITLE
Update pmmSettingsPage.js

### PR DESCRIPTION
**Pull request by BupycHuk**

### CODE REVIEW

**Comment by AlekSi** [comment]
@puneet0191 pmm-managed PR was merged

**Comment by puneet0191** [comment]
Thanks a lot, I request you to Please send PR to grafana-dashboard repo.

**Comment by AlekSi** [comment]
If those tests should not be there, then maybe remove them? So we are not confused.

**Comment by puneet0191** [comment]
yes, I will remove them

**Comment by BupycHuk** [comment]
@puneet0191 I'm PTO today, could you do it for me, please?

**Comment by puneet0191** [comment]
yes, I will do it

**Pull request closed without merging**
