### PR TITLE
PMM-3461 adding PMM tests from percona-qa

### PR DESCRIPTION
**Pull request by puneet0191**

### CODE REVIEW

**Comment by puneet0191** [comment]
@Nailya I deleted two folders 
1) pgsql 
2) MongoDb 

I was not sure why we need them directly in github Repo..since we download them via pmm-framework.sh anyways, if you think they are still needed I will add them back.

**Comment by rnovikovP** [comment]
should we merge this?

**Comment by Nailya** [comment]
@puneet0191 any objections? can we merge it?

**Comment by puneet0191** [comment]
well I have to update the code, many changes merged into pmm-tests folder since I sent this, so please wait on me to update it

**Comment by puneet0191** [comment]
okay updated, will need another round of merge, so not finalized, because of the changes I am making to pmm-framework.sh for postgresql plugin

**Comment by puneet0191** [comment]
sorry I have to close this PR.

**Pull request merged**
